### ISSUE TITLE
求资料推荐

### ISSUE THREAD

**Issue by Kaiyyyyy** [leleliu008/C-examples#6]
您好：
      可以推荐些C的书籍或者视频吗，java程序员想深入学习C/C++。

**Comment by leleliu008** [comment]
您好，我也没看过什么视频和书籍，我主要是看标准
https://pubs.opengroup.org/onlinepubs/9699919799/
https://en.cppreference.com/

另外，我个人觉得学习编程语言的目的是能够编写软件的话（不是为了研究语言特性），那么最好的学习就是在真实的项目中使用它，比如很多人学习了golang和rust之后，他们重新用这些语言编写那些经典的命令，或者实现更好的命令等等。你不需要先系统学习之后才开始使用它，而是让需求驱使你学习需要的知识，我写这些示例并不是为了学习他而写的，其实是我在真实项目中实践了之后写的，因为很多官方文档写的不详细，很多人可能根本看不明白。

**Comment by kaiybaby** [comment]
> 您好，我也没看过什么视频和书籍，我主要是看标准 https://pubs.opengroup.org/onlinepubs/9699919799/ https://en.cppreference.com/
> 
> 另外，我个人觉得学习编程语言的目的是能够编写软件的话（不是为了研究语言特性），那么最好的学习就是在真实的项目中使用它，比如很多人学习了golang和rust之后，他们重新用这些语言编写那些经典的命令，或者实现更好的命令等等。你不需要先系统学习之后才开始使用它，而是让需求驱使你学习需要的知识，我写这些示例并不是为了学习他而写的，其实是我在真实项目中实践了之后写的，因为很多官方文档写的不详细，很多人可能根本看不明白。

非感谢您的意见！
